### ISSUE TITLE
Host.js 

### ISSUE THREAD

**Issue by ani6gup** [Project6c613/platform#15]
## Main Components 

<img width="1277" alt="screen shot 2018-02-20 at 12 08 11 pm" src="https://user-images.githubusercontent.com/5401992/36443730-cc41fa16-1636-11e8-8b12-386592dceba8.png">

- Profile 
- Events 
- Details 
- Badge
- Announcements 
- Questions 

## ToDo 
- [ ] Read input and publish to database 
- Create New Event 
        - Use and understand callbacks 
        - Look at main.js messageform.submit
- [ ] Update database calls if you see anything missing 
- [ ] When Go Live is clicked, update database 
- [ ]  Figure out what queries need to be called if a user refreshes the page 
         - Keep Data Persistent

**Comment by sfallahadl** [comment]
[Working-Sessions.docx](https://github.com/Project6c613/platform/files/1755756/Working-Sessions.docx)
Document that shows how Reece and I solved the issues in detail. It goes over our ideas, solutions, and some bugs we found/solved.
