### ISSUE TITLE
Player.js

### ISSUE THREAD

**Issue by ani6gup** [Project6c613/platform#16]
## Main Components 

<img width="1248" alt="screen shot 2018-02-20 at 5 50 25 pm" src="https://user-images.githubusercontent.com/5401992/36457342-a8774fe8-1666-11e8-8ba3-b1aa64d33325.png">

- Profile 
- Events 
- Announcements 
- Questions 
- Game Clock

## ToDo 
- [ ] Read data from database to populate 
        - Announcements 
        - Questions 
- [ ] Update Questions (isSolved) in Database 
- [ ] Check if Questions are correct (if correct display popup, if incorrect display popup) 
- [ ] Update User Score for leaderboard transaction
- [ ] Create Leaderboard Database 
- [ ]  Load data if refresh (Figure out how to make data sustainable)

## Resources

- Ways of Reading Data 
1. Child Changed (Announcements) / Child Added / Child Removed
2. Transactions (Questions - isSolved - checkAnswer - update UserScore)
3. Snapshot /  On / Once (which you guys started out with) 

- [Writing and Reading Data in Firebase](https://firebase.google.com/docs/database/web/read-and-write)
- [Writing list of Data in Firebase](https://firebase.google.com/docs/database/web/lists-of-data)
- [Main.js in Quickstart](https://github.com/firebase/quickstart-js/blob/master/database/scripts/main.js)
- [You Got This! (Await and Async Calls)](http://issuu.com/yougotthis/docs/yougotthiszine?e=32705156/58395632)
- [Node.js Callbacks](https://www.tutorialspoint.com/nodejs/nodejs_callbacks_concept.htm)
- [Promises and Callbacks in Firebase](https://firebase.googleblog.com/2016/01/keeping-our-promises-and-callbacks_76.html)

### Code Snippets 

```
function showEvents(){
  //Loading Events
  var users = firebase.database().ref('/events/');
  users.child("details").once('value', getDetails);
  function getDetails(snapshot)
  {
    console.log(snapshot.val());
    snapshot.forEach(userSnapshot => {
       name = userSnapshot.val().eventName;
       name = userSnapshot.val().eventCode;
       time = userSnapshot.val().timeHr;
    });
    javascript:(function() {
      $axure('@eventsrepeater').addRepeaterData([
        {
          name: {type: 'text', text: 'name'},
          time: {type: 'text', text: 'time'},
          code: {type: 'text', text: 'code'},
        }
      ]).refreshRepeater();
    })();
  }
}

```

```
javascript:(function() {
  $axure('@questionsrepeater').addRepeaterData([
    {
      name: {type: 'text', text: 'Name'},
      isSolved: {type: 'text', text: 'false'},
      description: {type: 'text', text: 'description'},
      difficulty: {type: 'text', text: 'easy'},
      answer: {type: 'text', text: 'answer'},
      room: {type: 'text', text: 'Theater'},
    }
  ]).refreshRepeater();
})();
```
